# Generated by Django 4.1.7 on 2023-09-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='help',
        ),
    ]
